name: Code Quality Checks

on:
  push:

jobs:
  linting:
    name: Code Quality Checks
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip install "ruff" "mypy==1.5.1"

      - name: Code Linting
        run: ruff check django_markup

      - name: Code Formatting
        run: ruff format --check django_markup

      - name: Type Check
        run: mypy --install-types --non-interactive django_markup
